version: '3'

networks:
  desafio-network:
    driver: bridge

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - desafio-network

  app:
    build: 
      context: ./app
    container_name: app
    entrypoint: sh -c "npm install && npm run start"
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - desafio-network

  database:
    build: 
      context: ./database
    container_name: database
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
volumes:
  mysql:
    driver: local